import { useState } from "react";
import type { FormEvent } from "react";
import { useNavigate } from "react-router-dom";
import { apiFetch } from "../services/api";
type UploadState = { name: string; state: "pending" | "uploading" | "success" | "failed"; message?: string };
export default function NewClaim() {
  const navigate = useNavigate(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [files, setFiles] = useState<File[]>([]); const [uploads, setUploads] = useState<UploadState[]>([]);
  const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); setBusy(true); setError(""); try { const r = await apiFetch("/claims", { method: "POST", body: JSON.stringify({ title: f.get("title"), description: f.get("description"), claimedAmount: Number(f.get("claimedAmount")), policyId: f.get("policyId") || undefined }) }); if (!r.ok) throw new Error((await r.json()).message || "Could not submit claim"); const claim = await r.json(); setUploads(files.map(file => ({ name: file.name, state: "pending" }))); for (const file of files) { setUploads(prev => prev.map(x => x.name === file.name ? { ...x, state: "uploading" } : x)); const data = new FormData(); data.append("claimId", claim.id); data.append("file", file); data.append("description", "Evidence submitted with claim"); const upload = await apiFetch("/evidence/upload", { method: "POST", body: data }); setUploads(prev => prev.map(x => x.name === file.name ? { ...x, state: upload.ok ? "success" : "failed", message: upload.ok ? "Uploaded" : "Upload failed" } : x)); } setBusy(false); navigate(`/customer/claims/${claim.id}`); } catch (x) { setError(x instanceof Error ? x.message : "Could not submit claim"); setBusy(false); } };
  return <><p className="eyebrow">CUSTOMER PORTAL</p><h1>Submit a claim</h1><p className="muted intro">Submit your claim and upload multiple supporting documents in one step.</p>{error && <div className="alert error">{error}</div>}<form className="panel form" onSubmit={submit}><label>Claim title<input required name="title" placeholder="e.g. Water damage to kitchen" /></label><label>Claimed amount (₹)<input required min="0" step="0.01" type="number" name="claimedAmount" /></label><label>Policy ID <span className="muted">(optional)</span><input name="policyId" /></label><label>Description<textarea required minLength={10} name="description" rows={6} placeholder="Describe what happened and when." /></label><label>Evidence files <span className="muted">(optional, select multiple)</span><input type="file" multiple onChange={e => setFiles(Array.from(e.target.files || []))} /></label>{uploads.map(u => <div className="upload-status" key={u.name}><span>{u.name}</span><strong className={u.state}>{u.state === "uploading" ? "Uploading…" : u.message || u.state}</strong></div>)}<div className="form-actions"><button className="button" disabled={busy}>{busy ? (files.length ? "Submitting and uploading…" : "Submitting…") : "Submit claim"}</button><button type="button" className="button ghost" onClick={() => navigate("/customer")}>Cancel</button></div></form></>;
}
